[package]
name = "rust_cli_app"
version = "0.1.0"
authors = ["farooq-azam-khan-bdo <fkhan@bdo.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3" 

[[bin]]
name = "rust_cli_app"
path = "main.rs"
